// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package proxy represents the world "go:http/proxy@0.2.0".
//
// The `go:http/proxy` world implements a strict superset of `wasi:http/proxy`.
package proxy
