// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package proxy represents the world "wasi:http/proxy@0.2.0".
//
// The `wasi:http/proxy` world captures a widely-implementable intersection of
// hosts that includes HTTP forward and reverse proxies. Components targeting
// this world may concurrently stream in and out any number of incoming and
// outgoing HTTP requests.
package proxy
